// frontend_back/src/components/wizard/StepAdmin.vue
<script setup lang="ts">
import { reactive, ref } from 'vue'

import type { AdminInput } from '@/api/setup'

const admin = defineModel<AdminInput>({ required: true })
const confirmPassword = ref('')

const errors = reactive({
  firstName: '',
  lastName: '',
  email: '',
  password: '',
  confirmPassword: '',
})

function validate(): boolean {
  errors.firstName = admin.value.first_name.trim() ? '' : 'First name is required.'
  errors.lastName = admin.value.last_name.trim() ? '' : 'Last name is required.'
  errors.email = /^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(admin.value.email) ? '' : 'Enter a valid email address.'
  errors.password = admin.value.password.length >= 8 ? '' : 'Password must be at least 8 characters.'
  errors.confirmPassword = confirmPassword.value === admin.value.password ? '' : 'Passwords do not match.'

  return !errors.firstName && !errors.lastName && !errors.email && !errors.password && !errors.confirmPassword
}

defineExpose({ validate })
</script>

<template>
  <div>
    <h2 class="h5 fw-semibold mb-1">Administrator account</h2>
    <p class="small mb-4" style="color: var(--pb-text-muted)">
      This is the account you'll use to sign in and manage Playbook.
    </p>

    <div class="row g-3 mb-3">
      <div class="col-sm-6">
        <label class="form-label small fw-medium" for="admin-first-name">First name</label>
        <input
          id="admin-first-name"
          v-model="admin.first_name"
          type="text"
          class="form-control"
          :class="{ 'is-invalid': errors.firstName }"
          autocomplete="given-name"
        />
        <div v-if="errors.firstName" class="invalid-feedback d-block small">{{ errors.firstName }}</div>
      </div>
      <div class="col-sm-6">
        <label class="form-label small fw-medium" for="admin-last-name">Last name</label>
        <input
          id="admin-last-name"
          v-model="admin.last_name"
          type="text"
          class="form-control"
          :class="{ 'is-invalid': errors.lastName }"
          autocomplete="family-name"
        />
        <div v-if="errors.lastName" class="invalid-feedback d-block small">{{ errors.lastName }}</div>
      </div>
    </div>

    <div class="mb-3">
      <label class="form-label small fw-medium" for="admin-email">Email</label>
      <input
        id="admin-email"
        v-model="admin.email"
        type="email"
        class="form-control"
        :class="{ 'is-invalid': errors.email }"
        autocomplete="email"
      />
      <div v-if="errors.email" class="invalid-feedback d-block small">{{ errors.email }}</div>
    </div>

    <div class="row g-3">
      <div class="col-sm-6">
        <label class="form-label small fw-medium" for="admin-password">Password</label>
        <input
          id="admin-password"
          v-model="admin.password"
          type="password"
          class="form-control"
          :class="{ 'is-invalid': errors.password }"
          autocomplete="new-password"
        />
        <div v-if="errors.password" class="invalid-feedback d-block small">{{ errors.password }}</div>
      </div>
      <div class="col-sm-6">
        <label class="form-label small fw-medium" for="admin-confirm-password">Confirm password</label>
        <input
          id="admin-confirm-password"
          v-model="confirmPassword"
          type="password"
          class="form-control"
          :class="{ 'is-invalid': errors.confirmPassword }"
          autocomplete="new-password"
        />
        <div v-if="errors.confirmPassword" class="invalid-feedback d-block small">{{ errors.confirmPassword }}</div>
      </div>
    </div>
  </div>
</template>

// frontend/src/modules/setup/components/StepAdmin.tsx
import type { AdminInput } from '../api'
import type { AdminErrors } from './validators'

interface StepAdminProps {
  admin: AdminInput
  onChange: (patch: Partial<AdminInput>) => void
  confirmPassword: string
  onConfirmPasswordChange: (value: string) => void
  errors: AdminErrors
}

export default function StepAdmin({
  admin,
  onChange,
  confirmPassword,
  onConfirmPasswordChange,
  errors,
}: StepAdminProps) {
  return (
    <div>
      <h2 className="h5 fw-semibold mb-1">Administrator account</h2>
      <p className="small mb-4" style={{ color: 'var(--pb-text-muted)' }}>
        This is the account you&apos;ll use to sign in and manage Playbook.
      </p>

      <div className="row g-3 mb-3">
        <div className="col-sm-6">
          <label className="form-label small fw-medium" htmlFor="admin-first-name">
            First name
          </label>
          <input
            id="admin-first-name"
            type="text"
            className={`form-control ${errors.firstName ? 'is-invalid' : ''}`}
            autoComplete="given-name"
            value={admin.first_name}
            onChange={(e) => onChange({ first_name: e.target.value })}
          />
          {errors.firstName && <div className="invalid-feedback d-block small">{errors.firstName}</div>}
        </div>
        <div className="col-sm-6">
          <label className="form-label small fw-medium" htmlFor="admin-last-name">
            Last name
          </label>
          <input
            id="admin-last-name"
            type="text"
            className={`form-control ${errors.lastName ? 'is-invalid' : ''}`}
            autoComplete="family-name"
            value={admin.last_name}
            onChange={(e) => onChange({ last_name: e.target.value })}
          />
          {errors.lastName && <div className="invalid-feedback d-block small">{errors.lastName}</div>}
        </div>
      </div>

      <div className="mb-3">
        <label className="form-label small fw-medium" htmlFor="admin-email">
          Email
        </label>
        <input
          id="admin-email"
          type="email"
          className={`form-control ${errors.email ? 'is-invalid' : ''}`}
          autoComplete="email"
          value={admin.email}
          onChange={(e) => onChange({ email: e.target.value })}
        />
        {errors.email && <div className="invalid-feedback d-block small">{errors.email}</div>}
      </div>

      <div className="row g-3">
        <div className="col-sm-6">
          <label className="form-label small fw-medium" htmlFor="admin-password">
            Password
          </label>
          <input
            id="admin-password"
            type="password"
            className={`form-control ${errors.password ? 'is-invalid' : ''}`}
            autoComplete="new-password"
            value={admin.password}
            onChange={(e) => onChange({ password: e.target.value })}
          />
          {errors.password && <div className="invalid-feedback d-block small">{errors.password}</div>}
        </div>
        <div className="col-sm-6">
          <label className="form-label small fw-medium" htmlFor="admin-confirm-password">
            Confirm password
          </label>
          <input
            id="admin-confirm-password"
            type="password"
            className={`form-control ${errors.confirmPassword ? 'is-invalid' : ''}`}
            autoComplete="new-password"
            value={confirmPassword}
            onChange={(e) => onConfirmPasswordChange(e.target.value)}
          />
          {errors.confirmPassword && (
            <div className="invalid-feedback d-block small">{errors.confirmPassword}</div>
          )}
        </div>
      </div>
    </div>
  )
}
