// frontend/src/modules/setup/views/SetupView.tsx
import { useState } from 'react'
import { useNavigate } from 'react-router-dom'

import { ApiError } from '@/http/client'
import { completeSetup, type AdminInput, type InstanceInput } from '../api'
import WizardStepper from '../components/WizardStepper'
import StepWelcome from '../components/StepWelcome'
import StepAdmin from '../components/StepAdmin'
import StepInstance from '../components/StepInstance'
import StepFinish from '../components/StepFinish'
import { validateAdmin, validateInstance, type AdminErrors, type InstanceErrors } from '../components/validators'

const steps = ['Welcome', 'Administrator', 'Instance', 'Finish']

export default function SetupView() {
  const [currentStep, setCurrentStep] = useState(1)

  const [admin, setAdmin] = useState<AdminInput>({
    first_name: '',
    last_name: '',
    email: '',
    password: '',
  })
  const [confirmPassword, setConfirmPassword] = useState('')
  const [adminErrors, setAdminErrors] = useState<AdminErrors>({})

  const [instance, setInstance] = useState<InstanceInput>({
    name: '',
    timezone: Intl.DateTimeFormat().resolvedOptions().timeZone,
    locale: 'en',
  })
  const [instanceErrors, setInstanceErrors] = useState<InstanceErrors>({})

  const [submitting, setSubmitting] = useState(false)
  const [submitError, setSubmitError] = useState('')

  const navigate = useNavigate()

  function updateAdmin(patch: Partial<AdminInput>) {
    setAdmin((prev) => ({ ...prev, ...patch }))
  }

  function updateInstance(patch: Partial<InstanceInput>) {
    setInstance((prev) => ({ ...prev, ...patch }))
  }

  function next() {
    if (currentStep === 2) {
      const errors = validateAdmin(admin, confirmPassword)
      setAdminErrors(errors)
      if (Object.keys(errors).length > 0) return
    }

    if (currentStep === 3) {
      const errors = validateInstance(instance)
      setInstanceErrors(errors)
      if (Object.keys(errors).length > 0) return
    }

    setCurrentStep((step) => step + 1)
  }

  function back() {
    setSubmitError('')
    setCurrentStep((step) => step - 1)
  }

  async function finish() {
    setSubmitting(true)
    setSubmitError('')

    try {
      await completeSetup(admin, instance)
      navigate('/login')
    } catch (err) {
      setSubmitError(err instanceof ApiError ? err.message : 'Something went wrong. Please try again.')
    } finally {
      setSubmitting(false)
    }
  }

  return (
    <div className="pb-wizard-shell d-flex align-items-center justify-content-center p-3">
      <div className="pb-card pb-wizard-card border rounded-4 p-4 p-sm-5">
        <WizardStepper steps={steps} currentStep={currentStep} />

        {currentStep === 1 && <StepWelcome />}
        {currentStep === 2 && (
          <StepAdmin
            admin={admin}
            onChange={updateAdmin}
            confirmPassword={confirmPassword}
            onConfirmPasswordChange={setConfirmPassword}
            errors={adminErrors}
          />
        )}
        {currentStep === 3 && (
          <StepInstance instance={instance} onChange={updateInstance} errors={instanceErrors} />
        )}
        {currentStep === 4 && <StepFinish admin={admin} instance={instance} />}

        {submitError && (
          <div className="badge-danger-soft rounded-3 small mt-4 mb-0 py-2 px-3" role="alert">
            {submitError}
          </div>
        )}

        <div className="d-flex align-items-center gap-2 mt-4">
          {currentStep > 1 && (
            <button
              type="button"
              className="btn btn-sm pb-surface border"
              style={{ color: 'var(--pb-text-muted)' }}
              disabled={submitting}
              onClick={back}
            >
              Back
            </button>
          )}

          {currentStep < 4 ? (
            <button
              type="button"
              className="btn btn-primary btn-sm ms-auto fw-medium px-3"
              onClick={next}
            >
              {currentStep === 1 ? 'Get started' : 'Continue'}
            </button>
          ) : (
            <button
              type="button"
              className="btn btn-primary btn-sm ms-auto fw-medium px-3"
              disabled={submitting}
              onClick={finish}
            >
              {submitting && (
                <span
                  className="spinner-border spinner-border-sm me-2"
                  role="status"
                  aria-hidden="true"
                ></span>
              )}
              Finish setup
            </button>
          )}
        </div>
      </div>
    </div>
  )
}

// frontend/src/views/SetupView.vue
<script setup lang="ts">
import { ref } from 'vue'
import { useRouter } from 'vue-router'

import { ApiError } from '@/api/http'
import { completeSetup, type AdminInput, type InstanceInput } from '@/api/setup'
import WizardStepper from '@/components/wizard/WizardStepper.vue'
import StepWelcome from '@/components/wizard/StepWelcome.vue'
import StepAdmin from '@/components/wizard/StepAdmin.vue'
import StepInstance from '@/components/wizard/StepInstance.vue'
import StepFinish from '@/components/wizard/StepFinish.vue'

const steps = ['Welcome', 'Administrator', 'Instance', 'Finish']
const currentStep = ref(1)

const admin = ref<AdminInput>({ first_name: '', last_name: '', email: '', password: '' })
const instance = ref<InstanceInput>({ name: '', timezone: '', locale: 'en' })

const adminStepRef = ref<{ validate: () => boolean } | null>(null)
const instanceStepRef = ref<{ validate: () => boolean } | null>(null)

const submitting = ref(false)
const submitError = ref('')

const router = useRouter()

function next() {
  if (currentStep.value === 2 && !adminStepRef.value?.validate()) return
  if (currentStep.value === 3 && !instanceStepRef.value?.validate()) return

  currentStep.value++
}

function back() {
  submitError.value = ''
  currentStep.value--
}

async function finish() {
  submitting.value = true
  submitError.value = ''

  try {
    await completeSetup(admin.value, instance.value)
    await router.push({ name: 'login' })
  } catch (err) {
    submitError.value = err instanceof ApiError ? err.message : 'Something went wrong. Please try again.'
  } finally {
    submitting.value = false
  }
}
</script>

<template>
  <div class="pb-wizard-shell d-flex align-items-center justify-content-center p-3">
    <div class="pb-card pb-wizard-card border rounded-4 p-4 p-sm-5">
      <WizardStepper :steps="steps" :current-step="currentStep" />

      <StepWelcome v-if="currentStep === 1" />
      <StepAdmin v-else-if="currentStep === 2" ref="adminStepRef" v-model="admin" />
      <StepInstance v-else-if="currentStep === 3" ref="instanceStepRef" v-model="instance" />
      <StepFinish v-else :admin="admin" :instance="instance" />

      <div v-if="submitError" class="badge-danger-soft rounded-3 small mt-4 mb-0 py-2 px-3" role="alert">
        {{ submitError }}
      </div>

      <div class="d-flex align-items-center gap-2 mt-4">
        <button
          v-if="currentStep > 1"
          type="button"
          class="btn btn-sm pb-surface border"
          style="color: var(--pb-text-muted)"
          :disabled="submitting"
          @click="back"
        >
          Back
        </button>

        <button
          v-if="currentStep < 4"
          type="button"
          class="btn btn-primary btn-sm ms-auto fw-medium px-3"
          @click="next"
        >
          {{ currentStep === 1 ? 'Get started' : 'Continue' }}
        </button>

        <button
          v-else
          type="button"
          class="btn btn-primary btn-sm ms-auto fw-medium px-3"
          :disabled="submitting"
          @click="finish"
        >
          <span
            v-if="submitting"
            class="spinner-border spinner-border-sm me-2"
            role="status"
            aria-hidden="true"
          ></span>
          Finish setup
        </button>
      </div>
    </div>
  </div>
</template>
